export const proxyHostList = [
    "www.wikipedia.org",
    "www.wikibooks.org",
    "wikibooks.org",
    "m.wikipedia.org",
    "en.wikipedia.org",
    "en.m.wikipedia.org",
    "twitter.com",
    "t.co",
    "news.google.com",
    "developer.chrome.com",
    "www.bbc.com",
    "bbc.com",
    "blog.diigo.com",
    "diigo.com",
    "www.kali.org",
    "gutenberg.net.au",
    "golang.org",
    "developer.android.com",
    "www.bbc.co.uk",
    // "reactjs.org",
]
